
development:
    <<: *default
   adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: rutanio_production
    username: rails
    password: <%= ENV['RUTANIO_DATABASE_PASSWORD'] %>
