default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #postgres
  adapter: postgresql
  port: 5432

development:
  <<: *default
  # entorno desarrllo sqlite3
  # adapter: sqlite3
  # database: example_development
  #desarrollo:
  host: 167.71.182.161
  database: rutanio_production
  username: rails
  password: <%= ENV['RUTANIO_DATABASE_PASSWORD'] %>


test:
  <<: *default
  database: rutanio_test


production:
  <<: *default
  database: rutanio_production
  username: rails
  password: <%= ENV['RUTANIO_DATABASE_PASSWORD'] %>
