default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
    <<: *default
   adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: rutanio_production
    username: rails
    password: <%= ENV['RUTANIO_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: rutanio_test


production:
  <<: *default
  database: rutanio_production
  username: rails
  password: <%= ENV['RUTANIO_DATABASE_PASSWORD'] %>
